# Generated by Django 4.1.10 on 2023-10-25 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1040_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="due_date"
            ),
        ),
    ]
