# Generated by Django 4.1.10 on 2023-10-25 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1041_document_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="due_date"
            ),
        ),
    ]
