# Generated by Django 4.2.9 on 2024-01-14 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1044_document_due_date_log_due_date_and_more"),
        ("documents", "1044_workflow_workflowaction_workflowtrigger_and_more"),
    ]

    operations = []
