# Generated by Django 4.2.9 on 2024-02-24 13:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1045_merge_20240114_2134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="due_date",
            field=models.DateTimeField(
                default=None,
                null=True,
                verbose_name="due_date",
            ),
        ),
    ]
