# Generated by Django 4.2.11 on 2024-06-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1046_alter_document_due_date"),
        ("documents", "1048_alter_savedviewfilterrule_rule_type"),
    ]

    operations = []
