# Generated by Django 4.2.11 on 2024-06-16 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1045_merge_20240114_2134"),
        ("documents", "1048_alter_savedviewfilterrule_rule_type"),
    ]

    operations = []
