# Generated by Django 4.2.15 on 2024-08-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1049_merge_20240616_0853"),
        ("documents", "1051_alter_correspondent_owner_alter_document_owner_and_more"),
    ]

    operations = []
