# Generated by Django 5.1.4 on 2024-12-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1053_alter_legalentity_owner_alter_log_due_date_and_more"),
        ("documents", "1060_alter_customfieldinstance_value_select"),
    ]

    operations = []
